from . import back_home
from . import royhatdan_otish
from . import tugatish
from . import help
from . import admin
from . import start
from . import yangi_ustoz
from . import all_curses
from . import all_prodc
from . import send_vidio
